import { test, expect } from '@playwright/test';

test('test', async ({ page, request }) => {
  await page.goto('http://localhost:7150/');
  await page.goto('http://localhost:7150/Login');
  await page.getByLabel('Extension').click();
  await page.getByLabel('Extension').fill('1001');
  await page.getByLabel('Pin').click();
  await page.getByLabel('Pin').fill('1042')
  await page.getByLabel('Remember Me').check();
  await page.getByRole('button',{ name: 'Login' }).click();
  await page.getByLabel('Key').click();
  await page.getByLabel('Key').fill('c7c6d146-1aa4-4f1d-acc6-74-TESTUNIV18');
  await page.getByLabel('Customer Name').click();
  await page.getByLabel('Customer Name').fill('a');
  await page.getByLabel('Contact Name').click();
  await page.getByLabel('Contact Name').fill('a');
  await page.getByLabel('Address 1').fill('a');
  await page.getByLabel('Address 1').click();
  await page.getByLabel('Address 2').click();
  await page.getByLabel('Address 2').fill('a');
  await page.getByLabel('Address 3').click();
  await page.getByLabel('Address 3').fill('a');
  await page.getByLabel('City').click();
  await page.getByLabel('City').fill('a');
  await page.getByLabel('State / Province').click();
  await page.getByLabel('State / Province').fill('a');
  await page.getByLabel('Zip / Postal Code').fill('a');
  await page.getByLabel('Zip / Postal Code').click();
  await page.getByLabel('Country').click();
  await page.getByLabel('Country').fill('a');
  await page.getByLabel('Phone').click();
  await page.getByLabel('Phone').fill('a');
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').fill('a');
  await page.getByLabel('Reseller').click();
  await page.getByLabel('Reseller').fill('a');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('row', { name: 'Groups Wallboard' }).getByRole('checkbox').first().uncheck();
  await page.getByRole('row', { name: 'Groups Wallboard' }).getByRole('checkbox').first().check();
  await page.getByRole('row', { name: 'Groups Wallboard' }).locator('#chkOutbound').uncheck();
  await page.getByRole('row', { name: 'Groups Wallboard' }).locator('#chkOutbound').check();
  await page.getByRole('row', { name: 'Groups Wallboard' }).locator('#chkQueueCalls').uncheck();
  await page.getByRole('row', { name: 'Groups Wallboard' }).locator('#chkQueueCalls').check();
  await page.getByRole('row', { name: 'Groups Wallboard' }).locator('#chkQueueCalls').uncheck();
  await page.getByRole('row', { name: 'Groups Wallboard' }).locator('#chkQueueCalls').uncheck();
  await page.getByRole('row', { name: 'Groups Wallboard' }).locator('#chkQueueCalls').check();
  await page.locator('#chkPlayOnce').uncheck();
  await page.locator('#chkPlayOnce').check();
  await page.getByRole('row', { name: 'Groups Wallboard' }).locator('#txtFrequency').click();
  await page.getByRole('row', { name: 'Groups Wallboard' }).locator('#txtFrequency').fill('5');
  await page.getByRole('row', { name: 'Groups Wallboard' }).locator('#txtInitialDelay').click();
  await page.getByRole('row', { name: 'Groups Wallboard' }).locator('#txtInitialDelay').fill('5');
  await page.getByRole('row', { name: 'HOL Beep test' }).getByRole('cell').first().click();
  await page.getByRole('row', { name: 'HOL Beep test' }).locator('#chkcheckbox').check();
  await page.getByRole('row', { name: '8003 Wallbord' }).locator('#chkcheckbox').check();
  await page.getByRole('row', { name: '8016 recording Beep' }).locator('#chkcheckbox').check();
  await page.locator('.row > div:nth-child(2)').click();
  await page.getByLabel('Logout').click();
  await page.getByLabel('Logout').click();
  await page.goto('https://voiptoolswindowsdev03.my3cx.us:5001/webclient');
  await page.goto('https://voiptoolswindowsdev03.my3cx.us:5001/webclient/#/login');
  await page.getByPlaceholder('Extension number').click();
  await page.getByPlaceholder('Extension number').fill('1001');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').press('CapsLock');
  await page.getByPlaceholder('Password').fill('S');
  await page.getByPlaceholder('Password').press('CapsLock');
  await page.getByPlaceholder('Password').fill('Shivaay@1042');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Dialer' }).click();
  await page.getByPlaceholder('Enter name or number...').click();
  await page.getByPlaceholder('Enter name or number...').fill('3853311040');
  await page.locator('#btnCall').click();
  await page.getByRole('button', { name: 'Dialer' }).click();
  await page.getByPlaceholder('Enter name or number...').fill('3853311040');
  await page.locator('#btnCall').click();
  await page.getByRole('button', { name: 'Mute' }).click();
  await page.getByRole('img', { name: '1001' }).click();
  await page.locator('#menuLogout').click();
})

