import { test, expect } from '@playwright/test';

test('test', async ({ page, request }) => {
  await page.goto('http://localhost:7250/Login');
  await page.getByText('Logout').click();
  await page.getByPlaceholder('Extension').click();
  await page.getByPlaceholder('Extension').fill('1002');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('1042');
  await page.getByRole('row', { name: 'Remember Me:' }).locator('label').click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.goto('http://localhost:7250/License');
  await page.locator('#Key').click();
  await page.locator('#Key').fill('c7c6d146-1aa4-4f1d-acc6-74-TESTUNIV18');
  await page.locator('#CustName').click();
  await page.locator('#CustName').fill('a');
  await page.locator('#ContactName').click();
  await page.locator('#ContactName').click();
  await page.locator('#ContactName').fill('a');
  await page.locator('#Address1').click();
  await page.locator('#Address1').fill('a');
  await page.locator('#Address2').click();
  await page.locator('#Address2').fill('a');
  await page.locator('#Address3').click();
  await page.locator('#Address3').fill('a');
  await page.locator('#City').click();
  await page.locator('#City').fill('a');
  await page.locator('#State').click();
  await page.locator('#State').fill('a');
  await page.locator('#ZipCode').fill('a');
  await page.locator('#ZipCode').click();
  await page.locator('#Country').fill('a');
  await page.locator('#Country').click();
  await page.locator('#Phone').click();
  await page.locator('#Phone').fill('a');
  await page.locator('#Email').click();
  await page.locator('#Email').fill('a');
  await page.locator('#Reseller').click();
  await page.getByRole('row', { name: 'Reseller: *', exact: true }).getByRole('cell').nth(1).click();
  await page.locator('#Reseller').click();
  await page.locator('#Reseller').fill('a');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByRole('combobox').selectOption('Custom Presence Group');
  await page.locator('#CustomStatus').check();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('Settings updated successfully.').click();
  await page.getByLabel('Close popup').click();
  await page.getByRole('link', { name: 'Agents' }).click();
  await page.locator('#chkAgent').check();
  await page.locator('tr:nth-child(2) > td:nth-child(4) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(4) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(4) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(4) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(4) > input').fill('3');
  await page.locator('tr:nth-child(2) > td:nth-child(4) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(4) > input').fill('4');
  await page.locator('tr:nth-child(2) > td:nth-child(4) > input').click({
    clickCount: 6
  });
  await page.locator('tr:nth-child(2) > td:nth-child(4) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(4) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(4) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(5) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(5) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(5) > input').fill('4');
  await page.locator('tr:nth-child(2) > td:nth-child(5) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(5) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(5) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(5) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(5) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(5) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(5) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(5) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(6) > input').fill('3');
  await page.locator('tr:nth-child(2) > td:nth-child(6) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(6) > input').fill('7');
  await page.locator('tr:nth-child(2) > td:nth-child(6) > input').click({
    clickCount: 5
  });
  await page.locator('tr:nth-child(2) > td:nth-child(6) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(6) > input').fill('5');
  await page.locator('tr:nth-child(2) > td:nth-child(6) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(7) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(7) > input').fill('6');
  await page.locator('tr:nth-child(2) > td:nth-child(7) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(7) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(8) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(8) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(8) > input').fill('2');
  await page.locator('tr:nth-child(2) > td:nth-child(8) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(8) > input').fill('5');
  await page.locator('tr:nth-child(2) > td:nth-child(8) > input').click({
    clickCount: 6
  });
  await page.locator('tr:nth-child(2) > td:nth-child(9) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(9) > input').fill('4');
  await page.locator('tr:nth-child(2) > td:nth-child(9) > input').click({
    clickCount: 6
  });
  await page.locator('tr:nth-child(2) > td:nth-child(10) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(10) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(10) > input').fill('5');
  await page.locator('tr:nth-child(2) > td:nth-child(10) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(11) > input').dblclick();
  await page.locator('tr:nth-child(2) > td:nth-child(11) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(11) > input').fill('4');
  await page.locator('tr:nth-child(2) > td:nth-child(11) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(11) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(11) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(11) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(11) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(12) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(12) > input').fill('3');
  await page.locator('tr:nth-child(2) > td:nth-child(12) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(12) > input').fill('6');
  await page.locator('tr:nth-child(2) > td:nth-child(12) > input').click({
    clickCount: 5
  });
  await page.locator('tr:nth-child(2) > td:nth-child(12) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(12) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(12) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(12) > input').fill('5');
  await page.locator('tr:nth-child(2) > td:nth-child(12) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').fill('1');
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').fill('2');
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').fill('3');
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(13) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').fill('4');
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').fill('11');
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click({
    clickCount: 6
  });
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').fill('0');
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click({
    clickCount: 4
  });
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').fill('8');
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').fill('16');
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').fill('7');
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(14) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(15) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(15) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(15) > input').fill('3');
  await page.locator('tr:nth-child(2) > td:nth-child(15) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(15) > input').fill('4');
  await page.locator('tr:nth-child(2) > td:nth-child(15) > input').click({
    clickCount: 6
  });
  await page.locator('tr:nth-child(2) > td:nth-child(15) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(15) > input').click();
  await page.locator('tr:nth-child(2) > td:nth-child(15) > input').click();
  await page.getByRole('row', { name: '1002 VoIPTools' }).getByRole('combobox').selectOption('824-8243777_business-icon-establish-a-company-icon.png');
  await page.getByRole('link', { name: 'Wallboard' }).click();
  await page.getByRole('link', { name: 'Queues' }).click();
  await page.getByRole('link', { name: 'Agents' }).click();
  await page.getByRole('link', { name: 'Wallboard' }).click();
  await page.locator('tr:nth-child(31) > td:nth-child(37)').click();
  await page.goto('http://localhost:7250/Wallboard');
  await page.locator('tr:nth-child(5) > td:nth-child(33)').click();
  await page.locator('tr:nth-child(31) > td:nth-child(24)').click();
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowRight');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowRight');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowRight');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowRight');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowRight');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowRight');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowRight');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowRight');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowDown');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowDown');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowDown');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowUp');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowUp');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowDown');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowDown');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowDown');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowRight');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowRight');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.locator('body').filter({ hasText: '3CX Competitive Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('link', { name: 'General' }).click();
  await page.getByRole('link', { name: 'Wallboard' }).click();
  await page.getByRole('cell', { name: 'Jyoti Ranjan Tiwari 84 Test' }).click();
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('link', { name: 'General' }).click();
  await page.getByRole('link', { name: 'Wallboard' }).click();
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowUp');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowLeft');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByRole('link', { name: 'Wallboard' }).press('ArrowRight');
  await page.getByText('Logout', { exact: true }).click();
  await page.getByText('3CX Competitive Wallboard Login About').click();
});