import { test, expect } from '@playwright/test';

test('test', async ({ page, request }) => {
  await page.goto('http://localhost:7250/');
  await page.goto('http://localhost:7250/Index');
  await page.getByPlaceholder('Extension').click();
  await page.getByPlaceholder('Extension').fill('1002');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('1042');
  await page.getByRole('row', { name: 'Remember Me:' }).locator('label').click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('link', { name: 'General' }).click();
  await page.getByLabel('Calls').check();
  await page.getByLabel('Shifts').check();
  await page.getByLabel('Calls').check();
  await page.getByLabel('Calls').check();
  await page.getByRole('row', { name: 'Sort By: Calls Talk Time' }).locator('[id="\\31 "]').check();
  await page.getByRole('row', { name: 'Sort By: Calls Talk Time' }).locator('[id="\\32 "]').check();
  await page.getByRole('cell', { name: 'Calls Talk Time Agent' }).locator('[id="\\31 "]').check();
  await page.getByRole('cell', { name: 'Outbound Inbound' }).locator('[id="\\32 "]').check();
  await page.getByRole('cell', { name: 'Outbound Inbound' }).locator('[id="\\31 "]').check();
  await page.getByRole('cell', { name: 'Day Week Month' }).locator('[id="\\32 "]').check();
  await page.getByRole('cell', { name: 'Day Week Month' }).click();
  await page.locator('app body').getByRole('list').locator('div').filter({ hasText: '__DEFAULT__' }).locator('label').click();
  await page.locator('app body').getByRole('list').locator('div').filter({ hasText: '__DEFAULT__' }).locator('label').click();
  await page.locator('app body').getByRole('list').locator('div').filter({ hasText: 'Group Managers' }).locator('label').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByLabel('Close popup').click();
  await page.getByText('Logout', { exact: true }).click();
});